### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by preety889** [band-unfolding/bandup#10]
Dear All,
I have just started using Band Up code to unfold bandstructures. I have tried to unfold bandstructure of pristine supercell. For that i have supplied POSCARs of primitive cell and super cell and got the desired result. But in case of defects, where we generally make supercells, how can we define primitive cell? I'm a bit confused here. In case I take pristine primitive cell then the code gives error that they are not commensurate.
Any help would be highly appreciated.
Thanks and Regards

**Comment by stepan-tsirkin** [comment]
Dear @preety889 , have you already solved your issue? 

If not, you may post your POSCARs here. 

 I can only guess that your supercell was distorted by the defect, and therefore it is not commensurate with the pristine primitive cell. I general there are multiple ways to determine the PC, but it should be commensurate to the SC, i.e. the SC vectors should be expressable in the PC basis with integer coefficients. So, for a defected system, choose a PC which is close to the pristine PC, but commensurate  to the defected SC.

Regards,
Stepan.
