### ISSUE TITLE
Regarding use of bandup with  quantum espresso

### ISSUE THREAD

**Issue by vinpandey-hub** [band-unfolding/bandup#13]
Hi,
I am trying to unfold the band structure of a defect Nb0.8CoSb on its primitive fcc structure NbCoSb. 
I am facing few problems while unfolding as follows
1. it is not detecting the symmtery properly as NbCOSb has space group (F-43m) and it is detecting(F-m3m).
2. I am getting the error "Failed to determine GUR" while using flag unfold

Can you help me out?
thanks

**Comment by stepan-tsirkin** [comment]
Dear @vinpandey-hub ,

Is the problem appearing only with quantum espresso? can you try another ab-initio code? Just to know if it is a code-specific problem, or of a particular structure.

could you share you input files (or a minimal example that reproduces the same problem). I will try to investigate the problem.

Regards,
Stepan.

**Comment by vinpandey-hub** [comment]
Dear stepan-tsirkin,
Thanks for your reply
I dont have access to any other ab-intio code.  But I have checked the symmetries by quantum espresso and phonopy, both predicts correct symmetry. 
Since it is not supporting any data file.
I am putting it here
 primitive unit cell
NbCoSb  ! primitive cell vectors (fcc structure)
11.14371940  
  -0.506488876   -0.000000000   0.506488876
   0.000000000   0.506488876   0.506488876
   -0.506488876   0.506488876  -0.000000000

supercell 
Nb0.8CoSb  ! primitive supercell vectors (tetragonal structure)
13.8253363093d0
0.408248290464d0  -0.816496580928d0  0.408248290464d0
  -0.408248290464d0  0.816496580928d0  0.408248290464d0
  -0.816496580928d0  -0.408248290464d0  -0.408248290464d0

**Comment by stepan-tsirkin** [comment]
Dear @vinpandey-hub ,
you may share your input files (incl pseudopotentials) via external link to dropbox/googledrive or similar. Please include a bash script that executes the whole workflow that you are doing, and specify the version of quantum espresso that you are using.  Then I will investigate the problem. 

The difference between F-43 and F-m3m is the inversion symmetry. The group depends not only on lattice vectors, but also on coordinates of the atoms.

**Comment by stepan-tsirkin** [comment]
Also, I will feel more comfortable and more motivated  to assist, if I know your real name and institution that you represent.  Please, introduce yourself and/or complete your profile, if possible, unless you work for a secret service )).

**Comment by vinpandey-hub** [comment]
Dear sir, 
Thanks for your reply.
Please find the attached drive link below.
I am using a very old quantum espresso (5.0.3) as it is given in tutorial of bandup package.

https://drive.google.com/drive/folders/1_twaW4S2PAh8SjUxKeR9KXz_VDtAkB2t?usp=sharing

**Comment by stepan-tsirkin** [comment]
Dear Vineet ( @vinpandey-hub )

In order to restore support of fresh versions of QuantumEspresso and other codes, I am working on the purely pythonic version of bandUP - bandupy. it uses the functions to read and process bandstructures from the IrRep code. Please installit via 'pip install bandupy' and then run the script from the following example (after adjusting the pw.x  command to you system of course): https://www.dropbox.com/sh/od5dag48lowhjuc/AAAXY39b1TJuDmcOnH0Bej4pa?dl=0
It should work with the new versions of QE (I used v6.4.1), and probably will not work with the old ones. 

Please try it and report problems, if they arise.

Regards,
Stepan.

**Comment by stepan-tsirkin** [comment]
The pythonic version is now called banduppy and the repository is here : https://github.com/band-unfolding/banduppy
