### ISSUE TITLE
Fermi energy 

### ISSUE THREAD

**Issue by Pamodani** [band-unfolding/bandup#14]
Hi,
I am using VASP for my calculations. I did step1,step2, and step3 but when I typed bandup where I need to unfold the bands, it does not create an energy.info automatically. What could be the reason for it?
Thank you.

**Comment by stepan-tsirkin** [comment]
Dear @Pamodani,

Is it in the tutorial that the file is not created, or in your own calculation? If it is for your calculations, could you create a minimal example that reproduces the error (incl, all input files and a script/scripts to run)

Is there any error message? 


alternatively, you may try to install bandupy https://pypi.org/project/bandupy/ and follow an example from here: https://github.com/stepan-tsirkin/bandup/tree/bandupy/tutorial/Quantum_ESPRESSO_bandupy
(adapting to the VASP code)

Will it work for you?    

Regards,
Stepan.

**Comment by Pamodani** [comment]
Dear Stepan,
Thank you very much for your reply. I  tried again with bandup-master for
the bulk Si which was mentioned in tutorials section, Now I could make the
energy file. I ran the job file which was in step 4, then it automatically
created the energy file including the fermi energy. Now I am trying to use
it for my research.
Regards
Chapa.
