### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by sjjamsa** [band-unfolding/bandup#18]
Dear Bandup authors,

Have you tried making a pypi package out of bandup? Is there a reason why it would not work out?

That means, converting build into setup.py

It would make installation that much simpler!

Here is a relevant example:
https://stackoverflow.com/questions/55352409/python-setuptools-compile-fortran-code-and-make-an-entry-points

Best regards, 
 - Simppa -

**Comment by stepan-tsirkin** [comment]
Dear @sjjamsa , as you may notice, all original authors of BandUP have limited time to maintain the code. We try our best, but we welcome contributions from the community.  

If you have experience with that, please make a pull request, and we will further upload it to pupi, and your name will be acknowledged. 

Also, there is a purely pythonic implementation [banduppy](https://github.com/band-unfolding/banduppy), but it is a different code not using routines of the original bandUP, so functionalities may differ.

**Comment by sjjamsa** [comment]
Hi!

Thank you for your response. A colleague asked for help in installing bandup onto our cluster. He never followed up on the topic, so this issue has been dormant on my side as well.

I'll add a link to the python version to the near-forgotten ticket on our cluster.

I think I'll close this ticket here as well.

Cheerio!


 \- Simppa -
