### ISSUE TITLE
Postprocessing issue in BandUP V2.9.0

### ISSUE THREAD

**Issue by arrackad** [band-unfolding/bandup#20]
In the post unfolding utility, line 658 of the code 'plot_unfolded_EBS_BandUP.py' is: 'if symb_dict.has_key(input_list[i].upper()):'
However, this 'has_key()' was removed in python3 and it has to be replaced by '__ _contains_ __()'. It solved my problem. This is just a minor issue, I hope this will be helpful.

**Comment by stepan-tsirkin** [comment]
Hi @arrackad 
This, and many other compatibility issues are solved in the current master branch of the repository. 
please, install from it and use, and report problems that may arise with the new version.
