### ISSUE TITLE
Error when compiling (./build)

### ISSUE THREAD

**Issue by LOM-MSU** [band-unfolding/bandup#25]
We have tried compiling this program with two different computers, one was a fresh install of python, python3, pip, numpy, scipy, matplotlib, six, etc.

We are getting the same error for both computers:
`$ ./build
Traceback (most recent call last):
  File "./build", line 26, in <module>
    from bandupy.files import mkdir
  File "/home/lom/Documents/bandup-master/src/python_interface/bandupy/files.py", line 23, in <module>
    from scipy.constants import physical_constants
ImportError: No module named scipy.constants`

We have tried to change the code to things like "import scipy" with same error. It does not seem to recognize scipy. No internet searches have helped and we have puzzled over it for a long time without a clue. Any help would be appreciated. Thanks!

**Comment by stepan-tsirkin** [comment]
did you try `pip install scipy` ?

**Comment by stepan-tsirkin** [comment]
@LOM-MSU , have you resolved the issue ?  Do I understand correctly that you have installed scipy, but bandup "does not see it"? 

Can it be that the 'pip' end 'python'  point to different python's (e.g. the built-in and an anaconda) ?

**Comment by LOM-MSU** [comment]
> did you try `pip install scipy` ?

I think we did that... Cannot remember. I will ask.

> @LOM-MSU , have you resolved the issue ? Do I understand correctly that you have installed scipy, but bandup "does not see it"?
> 
> Can it be that the 'pip' end 'python' point to different python's (e.g. the built-in and an anaconda) ?

Hi @stepan-tsirkin, I will get back with the grad student on this and see if/how he resolved the issue.
