### ISSUE TITLE
UnicodeDecodeError  while generating SC k-path

### ISSUE THREAD

**Issue by Gargee-123** [band-unfolding/bandup#27]
Dear BandUP Developers, 

I am getting one error while generating SC k-path. Please help me to solve this problem. I have attached here the inputs. 

[step_2_get_kpts_to_be_used_in_the_SC_band_struc_calcs.zip](https://github.com/band-unfolding/bandup/files/7476062/step_2_get_kpts_to_be_used_in_the_SC_band_struc_calcs.zip)

Thanks & regards
Gargee

**===========================================================================
        BandUP: Band Unfolding code for Plane-wave based calculations      
    v3.0.0-beta.6-9-gbd3ff1f, 2021-04-13 18:34:21 +0200
    From Git branch: "master"
Compiled using Intel Fortran (ifort) V1910 on Thu Nov 04 10:39:07 2021
===========================================================================
Copyright (C) 2013-2017 Paulo V. C. Medeiros                               
                                                                           
                        Computational Physics Division                     
                        Department of Physics, Chemistry and Biology - IFM 
                        Link񯨮g University                               
                        Sweden                                             
                                                                           
                        Current address:                                   
                        University of Cambridge                            
                        Theory of Condensed Matter (TCM) Group             
                        Department of Physics                              
                        Cavendish Laboratory                               
                        Cambridge, UK                                      
                        Email: pvm20@cam.ac.uk                             
                                                                           
Please visit www.ifm.liu.se/theomod/compphys/band-unfolding                
===========================================================================
 
               Pre-processing utility "get_SCKPTS_pre_BandUP"
   >>> Getting the SC-KPTS you'll need for your plane-wave calc. <<<
 
 
 Checking if you are working with the smallest possible SC:
     * OK!
 
 Checking if working with the smallest possible ref. unit cell:
     * OK!
Traceback (most recent call last):
  File "/home/gargeeb/BandUP/bandup/bandup", line 73, in <module>
    run_requested_task(args)
  File "/home/gargeeb/BandUP/bandup/src/python_interface/bandupy/runners.py", line 73, in run_requested_task
    run_pre_bandup_tool(args)
  File "/home/gargeeb/BandUP/bandup/src/python_interface/bandupy/runners.py", line 53, in run_pre_bandup_tool
    for line in iter(bandup_pre_unf_run.stdout.readline, ''):
  File "/comm/swstack/core/anaconda3/2021.05/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 1556: invalid continuation byte**

**Comment by stepan-tsirkin** [comment]
Dear @Gargee-123 
Just as a try: if you change `encoding='UTF-8'` to `encoding='latin-1'` will the problem be solved for you?

If not, show the new error message

**Comment by Gargee-123** [comment]
Dear Stepan, 

I will check that and let you know about it.
