### ISSUE TITLE
Compatibility with Quantum Espresso 6.4.

### ISSUE THREAD

**Issue by jaki83** [band-unfolding/bandup#6]
There is a big issue related to work with never versions of Quantum Espresso.
As of version 6.4., QE does not support old file format any more (former -D_OLDXML option), so, right now, we are forced to stick with older versions of QE to use with BandUP.

Josip Jakovac

**Comment by zhibingao** [comment]
Dear Jakovac,

I have tested pwscf 6.4, 5.3, and 5.1 versions. They all failed with the same error:

Checking the symmetry of the SC...
    * Done.
    * Found 24 symmetry operations for the SC.
      * Symmetry group of the SC: D6h^1 (P6/mmm    ).
      * The SC symmetry has been determined using one of the associated PCs.
 
Checking the symmetry of the reference unit cell...
    * Done.
    * Found 24 pc symmetry operations.
      * Symmetry group of the pc: D6h^1 (P6/mmm    ).
      * The symmetry of your reference unit cell has been determined using one of the associated PCs.
 
# of pc-kpts requested along pcbz direction 1: 25
# of pc-kpts requested along pcbz direction 2: 25
# of pc-kpts requested along pcbz direction 3: 13
 
Symmetry analysis for the selected pcbz directions:
    >>> Direction #1:
        * Found 6 equivalent directions w.r.t. symmetry operations of the pc
        * Found 6 equivalent directions w.r.t. symmetry operations of the SC
        * No complementary pcbz directions are needed.
    >>> Direction #2:
        * Found 6 equivalent directions w.r.t. symmetry operations of the pc
        * Found 6 equivalent directions w.r.t. symmetry operations of the SC
        * No complementary pcbz directions are needed.
    >>> Direction #3:
        * Found 12 equivalent directions w.r.t. symmetry operations of the pc
        * Found 12 equivalent directions w.r.t. symmetry operations of the SC
        * No complementary pcbz directions are needed.
 
ERROR (get_SCKPTS_QE): Problems opening XML data-file!
########################################################################################################################
# WARNING: there are pending errors
# PENDING ERROR (ierr=1)
# ERROR IN: iotk_open_read (iotk_files.f90:611)
# CVS Revision: 1.20 
# unit
file=../step_3_get_SC_wavefunctions_to_be_used_for_unfolding/graphene_rectangular_SC.save/data-file.xml
binary=F
iostat=29
# PENDING ERROR (ierr=2)
# ERROR IN: iotk_open_read (iotk_files.f90:611)
# CVS Revision: 1.20 
# unit
file=../step_3_get_SC_wavefunctions_to_be_used_for_unfolding/graphene_rectangular_SC.save/data-file.xml
binary=F
iostat=29
# PENDING ERROR (ierr=3)
# ERROR IN: iotk_getline (iotk_scan.f90:947)
# CVS Revision: 1.23 
# 
iostat=29
# ERROR IN: iotk_scan_tag (iotk_scan.f90:593)
# CVS Revision: 1.23 
# ERROR IN: iotk_scan (iotk_scan.f90:821)
# CVS Revision: 1.23 
# ERROR IN: iotk_scan_begin (iotk_scan.f90:98)
# CVS Revision: 1.23 
# FROM IOTK LIBRARY, VERSION 1.2.0
# UNRECOVERABLE ERROR (ierr=4)
# ERROR IN: iotk_getline (iotk_scan.f90:947)
# CVS Revision: 1.23 
# 
iostat=29
# ERROR IN: iotk_scan_tag (iotk_scan.f90:593)
# CVS Revision: 1.23 
# ERROR IN: iotk_scan (iotk_scan.f90:821)
# CVS Revision: 1.23 
# ERROR IN: iotk_scan_begin (iotk_scan.f90:98)
# CVS Revision: 1.23 
########################################################################################################################

Could you please give me some kind suggestions? 
Thanks a lot!

Best wishes,
Zhibin

**Comment by stepan-tsirkin** [comment]
Dear @jaki83 , @zhibingao 

The support of newer versions of QE is resotored inthe python package "banduppy" . Please try it and report any problems on the corresponding repository: https://github.com/band-unfolding/banduppy
