### ISSUE TITLE
about Orbital Projection for VASP

### ISSUE THREAD

**Issue by zanat** [band-unfolding/bandup#9]
Hi all,
When I run a projection for d orbitals I get as information : 
` * OrbitalProjector: dxy+dyz+dz2+dxz`
is dx2-y2 not included? 
when I specify dx2 only i get 
`Invalid choice of orbital: "dx2" `

**Comment by zanat** [comment]
Resolved, a workaround to this issue by the adaptation of vasp output files to bandup notation
`sed -i 's/x2-y2/dx2/'  PROCAR`

**Comment by cai-xiaomeng** [comment]
Hi, @zanat 
How to write the orbital projection command? I see from the manual that before orbital projection, I should first get unfolding-density operator file. And how to write the command to get this? Should I get this unfolding-density operator file in step_3_get_sc_wavefunctions directory or somewhere else? 
Thank you so much!!!  Looking forward to hearing from you!!!

**Comment by cai-xiaomeng** [comment]
> Hi, @zanat
> How to write the orbital projection command? I see from the manual that before orbital projection, I should first get unfolding-density operator file. And how to write the command to get this? Should I get this unfolding-density operator file in step_3_get_sc_wavefunctions directory or somewhere else?
> Thank you so much!!! Looking forward to hearing from you!!!

I always get this error "FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-umjzhh/umjzhh-1/step_4_run_BandUP_and_plot/orbital_projections/KptsInfo_iSpin_1.pkl"

**Comment by zanat** [comment]
Salam,
For help try:
`bandup projected-unfold  -h`

then set task to:
`task='projected-unfold'`
in run_BandUP_unfold_and_plot_tasks.sh script
good luck

**Comment by cai-xiaomeng** [comment]
Thank you so much for your reply!!!  But I tried and still get the error "FileNotFoundError: KptsInfo_iSpin_1.pkl".

![11451618970003_ pic](https://user-images.githubusercontent.com/62108718/115485492-727cd380-a287-11eb-9473-6e934d5d2259.jpg)
![11461618970073_ pic](https://user-images.githubusercontent.com/62108718/115485613-a7892600-a287-11eb-9116-473d21f5a824.jpg)
![11471618970469_ pic](https://user-images.githubusercontent.com/62108718/115486106-8d9c1300-a288-11eb-9316-dca480077d56.jpg)

**Comment by zanat** [comment]
try with:
`-results_dir RESULTS_DIR`
and specify your RESULTS_DIR as your current working directory /lustre/........./step_4_run....../
and you must notice that PROCAR must be generated from previous run of step_3
